# Site settings
title: Shaishav Parekh
email: shaishavparekh at gmail dot com

description: Software Developer & a Hokie.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shaishavparekh.com" # the base hostname & protocol for your site
github_username:  smparekh
linkedin_username: shaishavparekh



# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

# Github stuff
safe: true
lsi: false
source: .

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
